sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8
  - 6
branches:
  only:
    - master
notifications:
  email: false
scripts:
  - npm run-all
after_success:
  - npm run report-coverage
  - npm run release
