sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: 6
branches:
  only:
    - master
notifications:
  email: false
scripts:
  - npm run
after_success:
  - npm run report-coverage
