sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8
branches:
  only:
    - master
notifications:
  email: false
scripts:
  - yarn run-all
after_success:
  - yarn report-coverage
