sudo: false
language: node_js

cache:
  directories:
    - node_modules

node_js:
  - 8

notifications:
  email: false

scripts:
  - yarn format
  - yarn lint
  - yarn build
  - yarn coverage

after_success:
  - yarn report-coverage
